on:
    push:
    workflow_dispatch:
    repository_dispatch:
        types: [dependency_update]

name: Generar STATIC y ftp

jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get latest code
              uses: actions/checkout@v2

            - name: Use Node.js 18
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Build Project
              run: |
                  npm install
                  npm run build
              env:
                  STORYBLOK_TOKEN_PROD: $STORYBLOK_TOKEN_PROD
                  STORYBLOK_TOKEN_PREV: $STORYBLOK_TOKEN_PREV
                  STORYBLOK_TOKEN: $STORYBLOK_TOKEN

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.2.0
              with:
                  server: melborp.art
                  username: mbp
                  password: ${{ secrets.ftp_password }}
                  local-dir: ./dist
                  server-dir: /astro.melborp.art/
                  dangerous-clean-slate: false
